title: PlantUML
name: plantuml
description: PlantUML is a component that allows you to create various UML diagrams through simple textual descriptions. From sequence diagrams to deployment diagrams and beyond, PlantUML provides an easy way to create visual representations of complex systems.
summary: Create UML diagrams and other type of diagrams directly from plain text.

base: core24
contact:
  - jassielovando@protonmail.com
  - https://github.com/jassielof/plantuml-snap
donation: https://github.com/plantuml/plantuml # On sponsor
website: https://plantuml.com/
source-code: "https://github.com/jassielof/plantuml-snap"
issues: "https://github.com/jassielof/plantuml-snap/issues"
version: "1.2026.1"
license: GPL-3.0+
icon: assets/images/icon.svg

grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

apps:
  plantuml:
    command: bin/plantuml-wrapper
    plugs:
      - home
      - removable-media
      - network
    environment:
      # JAVA_HOME: $SNAP/java
      PATH: $SNAP/usr/bin:$PATH
      GRAPHVIZ_DOT: $SNAP/usr/bin/dot

  plantuml-gui:
    command: bin/plantuml-gui-wrapper --gui
    desktop: share/applications/plantuml.desktop
    extensions: [gnome]
    plugs:
      - home
      - removable-media
      - network
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - unity7
      - opengl
    environment:
      PATH: $SNAP/usr/bin:$PATH
      GRAPHVIZ_DOT: $SNAP/usr/bin/dot
      # JAVA_HOME: $SNAP/java
      _JAVA_OPTIONS: "-Duser.home=$SNAP_USER_DATA -Djava.util.prefs.userRoot=$SNAP_USER_DATA/.java/.userPrefs"

parts:
  graphviz:
    plugin: autotools
    source-depth: 1
    source: https://gitlab.com/graphviz/graphviz.git
    source-tag: "14.1.2"
    build-packages:
      - build-essential
      - cmake
      - bison
      - flex
      - libexpat1-dev
      - libgd-dev
      - libcairo2-dev
      - libpango1.0-dev
      - libgts-dev
      - pkg-config
    stage-packages:
      - libexpat1
      - libgd3
      - libcairo2
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libgts-0.7-5
    autotools-configure-parameters:
      - --prefix=/usr
  plantuml:
    plugin: nil
    after: [graphviz]
    source: .
    build-packages:
      - curl
    stage-packages:
      - openjdk-25-jre
      # - graphviz # TODO: Update core24 to core26 when available, since core24 has a very old version of graphviz and core26 will finally update it.

    override-build: bash scripts/build.bash
  plantuml-gui:
    plugin: dump
    source: .
    organize:
      assets/gui/plantuml.desktop: share/applications/plantuml.desktop
      assets/images/icon.svg: share/icons/hicolor/scalable/apps/plantuml.svg
    stage:
      - share/applications/plantuml.desktop
      - share/icons/hicolor/scalable/apps/plantuml.svg
